remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already h
title: pfahlr.github.io | Rick Pfahl's Github Pages Site
tagline: Welcome to pfahlr.github.io
description: pfahlr.github.io - articles and guides about various subjects in computer science. 
show_downloads: "false"
#google_analytics: [Your Google Analytics tracking ID]

